In [5]:
import os
os.listdir()

['drug-enforcement-0001-of-0001.json.zip',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'drug-shortages-0001-of-0001.json.zip',
 '.ipynb_checkpoints',
 'drug-ndc-0001-of-0001.json.zip']

In [6]:
import zipfile

with zipfile.ZipFile("drug-shortages-0001-of-0001.json.zip", "r") as z:
    print(z.namelist())

['drug-shortages-0001-of-0001.json']

In [7]:
import json

with zipfile.ZipFile("drug-shortages-0001-of-0001.json.zip", "r") as z:
    with z.open("drug-shortages-0001-of-0001.json") as f:
        data = json.load(f)

print(data.keys())

dict_keys(['meta', 'results'])

In [8]:
print("Number of shortage records:", len(data["results"]))

Number of shortage records: 1601

In [9]:
data["results"][0]

{'update_type': 'Reverified',
 'initial_posting_date': '04/02/2020',
 'package_ndc': '0409-2596-05',
 'generic_name': 'Midazolam Hydrochloride Injection',
 'contact_info': '844-646-4398',
 'availability': 'Available',
 'openfda': {'application_number': ['ANDA075293'],
  'brand_name': ['MIDAZOLAM'],
  'generic_name': ['MIDAZOLAM HYDROCHLORIDE'],
  'manufacturer_name': ['Hospira, Inc.'],
  'product_ndc': ['0409-2596', '0409-2587'],
  'product_type': ['HUMAN PRESCRIPTION DRUG'],
  'route': ['INTRAMUSCULAR', 'INTRAVENOUS'],
  'substance_name': ['MIDAZOLAM HYDROCHLORIDE'],
  'rxcui': ['311700', '311702'],
  'spl_id': ['6c075a2d-b68b-41a7-aa0c-bcf9894e3f76'],
  'spl_set_id': ['affecd4d-1f78-4bbe-5a8d-86849bbdc520'],
  'package_ndc': ['0409-2587-04',
   '0409-2587-05',
   '0409-2596-13',
   '0409-2596-03',
   '0409-2596-15',
   '0409-2596-05'],
  'unii': ['W7TTW573JJ']},
 'update_date': '09/22/2026',
 'therapeutic_category': ['Anesthesia', 'Neurology'],
 'dosage_form': 'Injection',
 'presentation': 'Midazolam Hydrochloride, Injection, 50 mg/10 mL (5 mg/mL) (NDC 0409-2596-05)',
 'company_name': 'Hospira, Inc., a Pfizer Company',
 'status': 'Current'}

In [10]:
import pandas as pd

shortages = pd.json_normalize(data["results"])

print("Rows:", shortages.shape[0])
print("Columns:", shortages.shape[1])

shortages.head()

Rows: 1601
Columns: 36

,update_type,initial_posting_date,package_ndc,generic_name,contact_info,availability,update_date,therapeutic_category,dosage_form,presentation,...,shortage_reason,openfda.nui,openfda.pharm_class_pe,openfda.pharm_class_epc,discontinued_date,related_info_link,openfda.pharm_class_cs,change_date,openfda.pharm_class_moa,resolved_note
0,Reverified,04/02/2020,0409-2596-05,Midazolam Hydrochloride Injection,844-646-4398,Available,09/22/2026,"[Anesthesia, Neurology]",Injection,"Midazolam Hydrochloride, Injection, 50 mg/10 m...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Reverified,01/19/2023,62135-484-60,Quinapril Hydrochloride Tablet,845-268-5000 x 510 or Chartwell Customer servi...,Available,09/15/2026,[Cardiovascular],Tablet,"Quinapril Hydrochloride, Tablet, 5 mg (NDC 621...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Revised,04/07/2020,23155-473-42,Furosemide Injection,855-228-9470,Unavailable,09/01/2026,[Cardiovascular],Injection,"Furosemide, Injection, 10 mg/1 mL (NDC 23155-4...",...,Other,"[N0000175366, N0000175590]",[Increased Diuresis at Loop of Henle [PE]],[Loop Diuretic [EPC]],NaN,NaN,NaN,NaN,NaN,NaN
3,Reverified,03/23/2018,63323-286-20,Ropivacaine Hydrochloride Injection,888-386-1300,Unavailable,09/15/2026,[Anesthesia],Injection,"Naropin, Injection, 5 mg/1 mL (NDC 63323-286-20)",...,Delay in shipping of the drug,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,New,02/25/2026,0009-0225-02,Clindamycin Hydrochloride Capsule,844-646-4398,NaN,02/25/2026,[Anti-Infective],Capsule,"Cleocin Hydrochloride, Capsule, 150 mg (NDC 00...",...,NaN,NaN,NaN,NaN,02/25/2026,NaN,NaN,NaN,NaN,NaN

In [11]:
for column in shortages.columns:
    print(column)

update_type
initial_posting_date
package_ndc
generic_name
contact_info
availability
update_date
therapeutic_category
dosage_form
presentation
company_name
status
openfda.application_number
openfda.brand_name
openfda.generic_name
openfda.manufacturer_name
openfda.product_ndc
openfda.product_type
openfda.route
openfda.substance_name
openfda.rxcui
openfda.spl_id
openfda.spl_set_id
openfda.package_ndc
openfda.unii
related_info
shortage_reason
openfda.nui
openfda.pharm_class_pe
openfda.pharm_class_epc
discontinued_date
related_info_link
openfda.pharm_class_cs
change_date
openfda.pharm_class_moa
resolved_note

In [12]:
shortages.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1601 entries, 0 to 1600
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   update_type                 1601 non-null   object
 1   initial_posting_date        1601 non-null   object
 2   package_ndc                 1601 non-null   object
 3   generic_name                1601 non-null   object
 4   contact_info                1601 non-null   object
 5   availability                1153 non-null   object
 6   update_date                 1601 non-null   object
 7   therapeutic_category        1601 non-null   object
 8   dosage_form                 1581 non-null   object
 9   presentation                1601 non-null   object
 10  company_name                1601 non-null   object
 11  status                      1601 non-null   object
 12  openfda.application_number  1384 non-null   object
 13  openfda.brand_name          1412 non-null   object
 14  openfda.generic_name        1412 non-null   object
 15  openfda.manufacturer_name   1412 non-null   object
 16  openfda.product_ndc         1412 non-null   object
 17  openfda.product_type        1412 non-null   object
 18  openfda.route               1403 non-null   object
 19  openfda.substance_name      1402 non-null   object
 20  openfda.rxcui               1375 non-null   object
 21  openfda.spl_id              1412 non-null   object
 22  openfda.spl_set_id          1412 non-null   object
 23  openfda.package_ndc         1412 non-null   object
 24  openfda.unii                1405 non-null   object
 25  related_info                1099 non-null   object
 26  shortage_reason             411 non-null    object
 27  openfda.nui                 359 non-null    object
 28  openfda.pharm_class_pe      93 non-null     object
 29  openfda.pharm_class_epc     358 non-null    object
 30  discontinued_date           441 non-null    object
 31  related_info_link           35 non-null     object
 32  openfda.pharm_class_cs      163 non-null    object
 33  change_date                 11 non-null     object
 34  openfda.pharm_class_moa     124 non-null    object
 35  resolved_note               6 non-null      object
dtypes: object(36)
memory usage: 450.4+ KB

In [13]:
shortages["status"].value_counts(dropna=False)

status
Current               1153
To Be Discontinued     441
Resolved                 7
Name: count, dtype: int64

In [15]:
shortages["company_name"].value_counts().head(20)
shortages["shortage_reason"].value_counts().head(20)
shortages["therapeutic_category"].value_counts().head(20)

therapeutic_category
[Anesthesia]                                                                                                                                         257
[Psychiatry]                                                                                                                                         231
[Cardiovascular]                                                                                                                                     147
[Analgesia/Addiction]                                                                                                                                114
[Anti-Infective]                                                                                                                                      86
[Oncology]                                                                                                                                            81
[Anesthesia, Pediatric]                                                                                                                               66
[Endocrinology/Metabolism, Gastroenterology, Other, Pediatric]                                                                                        53
[Neurology]                                                                                                                                           43
[Neurology, Pediatric, Psychiatry]                                                                                                                    40
[Endocrinology/Metabolism]                                                                                                                            37
[Rheumatology]                                                                                                                                        36
[Gastroenterology]                                                                                                                                    33
[Anesthesia, Neurology]                                                                                                                               27
[Hematology]                                                                                                                                          25
[Renal]                                                                                                                                               25
[Analgesia/Addiction, Pediatric]                                                                                                                      24
[Other]                                                                                                                                               21
[Dermatology, Endocrinology/Metabolism, Gastroenterology, Hematology, Neurology, Oncology, Ophthalmology, Other, Pulmonary/Allergy, Rheumatology]     19
[Endocrinology/Metabolism, Gastroenterology, Pediatric]                                                                                               19
Name: count, dtype: int64

In [16]:
missing = pd.DataFrame({
    "Missing_Count": shortages.isna().sum(),
    "Missing_Percent": (shortages.isna().sum() / len(shortages) * 100).round(2)
})

missing.sort_values("Missing_Percent", ascending=False)

                            Missing_Count  Missing_Percent
resolved_note                        1595            99.63
change_date                          1590            99.31
related_info_link                    1566            97.81
openfda.pharm_class_pe               1508            94.19
openfda.pharm_class_moa              1477            92.25
openfda.pharm_class_cs               1438            89.82
openfda.pharm_class_epc              1243            77.64
openfda.nui                          1242            77.58
shortage_reason                      1190            74.33
discontinued_date                    1160            72.45
related_info                          502            31.36
availability                          448            27.98
openfda.rxcui                         226            14.12
openfda.application_number            217            13.55
openfda.substance_name                199            12.43
openfda.route                         198            12.37
openfda.unii                          196            12.24
openfda.generic_name                  189            11.81
openfda.product_type                  189            11.81
openfda.brand_name                    189            11.81
openfda.spl_id                        189            11.81
openfda.spl_set_id                    189            11.81
openfda.package_ndc                   189            11.81
openfda.product_ndc                   189            11.81
openfda.manufacturer_name             189            11.81
dosage_form                            20             1.25
initial_posting_date                    0             0.00
update_type                             0             0.00
generic_name                            0             0.00
package_ndc                             0             0.00
therapeutic_category                    0             0.00
presentation                            0             0.00
company_name                            0             0.00
status                                  0             0.00
update_date                             0             0.00
contact_info                            0             0.00

In [17]:
print("Total records:", len(shortages))

print(
    "Unique package NDCs:",
    shortages["package_ndc"].nunique()
)

print(
    "Missing package NDCs:",
    shortages["package_ndc"].isna().sum()
)

Total records: 1601
Unique package NDCs: 1570
Missing package NDCs: 0

In [18]:
date_columns = [
    "initial_posting_date",
    "update_date",
    "change_date"
]

for column in date_columns:
    if column in shortages.columns:
        print(column)
        print(shortages[column].head())
        print()

initial_posting_date
0    04/02/2020
1    01/19/2023
2    04/07/2020
3    03/23/2018
4    02/25/2026
Name: initial_posting_date, dtype: object

update_date
0    09/22/2026
1    09/15/2026
2    09/01/2026
3    09/15/2026
4    02/25/2026
Name: update_date, dtype: object

change_date
0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: change_date, dtype: object